export interface TravelPackage {
  id: string;
  title: string;
  location: string;
  description: string;
  duration: string;
  price: string;
  image: string;
  duration_days?: number;
  duration_nights?: number;
  pax_min?: number | null;
  pax_max?: number | null;
  accommodation_type?: string | null;
  star_rating?: number;
  review_rating?: number | null;
  review_count?: number;
  type?: string;
}

export const POPULAR_PACKAGES: TravelPackage[] = [
  {
    id: "maldives-luxury",
    title: "Maldives Luxury Escape",
    location: "Maldives",
    description: "Experience the epitome of relaxation in private water villas, surrounded by azure lagoons and pristine beaches.",
    duration: "4 Nights 5 Days",
    price: "৳ 120,000",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    duration_days: 5,
    duration_nights: 4,
    pax_min: 2,
    pax_max: 10,
    accommodation_type: "Resort",
    star_rating: 5,
    review_rating: 4.9,
    review_count: 357,
    type: "international",
  },
  {
    id: "premium-umrah",
    title: "Premium Umrah Experience",
    location: "Saudi Arabia",
    description: "A spiritually fulfilling journey with premium accommodations near the Haram, dedicated transport, and expert guidance.",
    duration: "14 Nights 15 Days",
    price: "৳ 165,000",
    image: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800&q=80",
    duration_days: 15,
    duration_nights: 14,
    pax_min: 1,
    pax_max: 40,
    accommodation_type: "5-Star Hotel",
    star_rating: 5,
    review_rating: 5.0,
    review_count: 1240,
    type: "umrah",
  },
  {
    id: "sylhet-eco",
    title: "Sylhet Eco-Adventure",
    location: "Bangladesh",
    description: "Discover the lush tea gardens, serene wetlands, and vibrant local culture in this immersive eco-tour.",
    duration: "3 Nights 4 Days",
    price: "৳ 25,000",
    image: "inbound/sylhet.jpg",
    duration_days: 4,
    duration_nights: 3,
    pax_min: 4,
    pax_max: 12,
    accommodation_type: "Eco-Resort",
    star_rating: 4,
    review_rating: 4.8,
    review_count: 215,
    type: "inbound",
  },
  {
    id: "bali-retreat",
    title: "Bali Cultural Retreat",
    location: "Indonesia",
    description: "Explore majestic temples, vibrant rice terraces, and beautiful beaches in this comprehensive Bali tour.",
    duration: "5 Nights 6 Days",
    price: "৳ 75,000",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    duration_days: 6,
    duration_nights: 5,
    pax_min: 2,
    pax_max: 20,
    accommodation_type: "Villa",
    star_rating: 5,
    review_rating: 4.7,
    review_count: 430,
    type: "international",
  },
  {
    id: "thailand-discovery",
    title: "Thailand Discovery",
    location: "Thailand",
    description: "A perfect blend of city tours in Bangkok and relaxing beach days in Phuket and Krabi.",
    duration: "4 Nights 5 Days",
    price: "৳ 55,000",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80",
    duration_days: 5,
    duration_nights: 4,
    pax_min: 2,
    pax_max: 30,
    accommodation_type: "Hotel",
    star_rating: 4,
    review_rating: 4.6,
    review_count: 580,
    type: "international",
  },
  {
    id: "sundarbans-safari",
    title: "Sundarbans Wildlife Safari",
    location: "Bangladesh",
    description: "Navigate through the world's largest mangrove forest and witness diverse wildlife in their natural habitat.",
    duration: "2 Nights 3 Days",
    price: "৳ 18,000",
    image: "/inbound/tiger.jpg", 
    duration_days: 3,
    duration_nights: 2,
    pax_min: 10,
    pax_max: 40,
    accommodation_type: "Cruise Ship",
    star_rating: 4,
    review_rating: 4.8,
    review_count: 310,
    type: "inbound",
  },
  {
    id: "dubai-city",
    title: "Dubai City Escapade",
    location: "UAE",
    description: "Experience the ultimate modern luxury, from towering skyscrapers to desert safaris and premium shopping.",
    duration: "3 Nights 4 Days",
    price: "৳ 85,000",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    duration_days: 4,
    duration_nights: 3,
    pax_min: 2,
    pax_max: 15,
    accommodation_type: "Hotel",
    star_rating: 5,
    review_rating: 4.9,
    review_count: 890,
    type: "international",
  },
  {
    id: "short-umrah",
    title: "Short Umrah Package",
    location: "Saudi Arabia",
    description: "A compact, highly organized Umrah package for those with limited time but seeking a fulfilling experience.",
    duration: "6 Nights 7 Days",
    price: "৳ 110,000",
    image: "umrah/mecca.jpg",
    duration_days: 7,
    duration_nights: 6,
    pax_min: 1,
    pax_max: 30,
    accommodation_type: "Hotel",
    star_rating: 4,
    review_rating: 4.8,
    review_count: 650,
    type: "umrah",
  },
  {
    id: "swiss-alps",
    title: "Swiss Alps Adventure",
    location: "Switzerland",
    description: "Breathtaking mountain views, scenic train rides, and charming alpine villages await you.",
    duration: "6 Nights 7 Days",
    price: "৳ 210,000",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&q=80",
    duration_days: 7,
    duration_nights: 6,
    pax_min: 2,
    pax_max: 12,
    accommodation_type: "Lodge",
    star_rating: 5,
    review_rating: 5.0,
    review_count: 145,
    type: "international",
  },
  {
    id: "corporate-tour",
    title: "Corporate Tour Package",
    location: "Worldwide",
    description: "Purpose-built retreats, incentive trips, and offsites for teams — from venue and logistics to activities, all handled end-to-end.",
    duration: "3 Nights 4 Days",
    price: "৳ 45,000",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80",
    duration_days: 4,
    duration_nights: 3,
    pax_min: 10,
    pax_max: 100,
    accommodation_type: "Business Hotel",
    star_rating: 4,
    review_rating: 4.7,
    review_count: 96,
    type: "corporate",
  },
];
